[phases.setup]
nixPkgs = ["python311", "nodejs-18_x", "yarn", "pip"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r backend/requirements.txt",
  "cd frontend && yarn install"
]

[phases.build]
cmds = [
  "cd frontend && yarn build"
]

[start]
cmd = "python -m uvicorn backend.server:app --host 0.0.0.0 --port $PORT"