[phases.setup]
nixPkgs = ["python3", "python3Packages.pip"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r backend/requirements.txt"
]

[start]
cmd = "cd backend && python3 -m uvicorn server:app --host 0.0.0.0 --port $PORT"