[phases.setup]
nixPkgs = ["python310", "nodejs-18_x", "yarn"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "cd frontend && yarn install"
]

[phases.build]
cmds = [
  "cd frontend && yarn build"
]

[start]
cmd = "python -m uvicorn backend.server:app --host 0.0.0.0 --port $PORT"